### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by 1079658109** [cpnota/autonomous-learning-library#267]
dear friend:
I need your help,I encountered the following error
Traceback (most recent call last):
  File "D:/RL-MPC-LaneMerging-master/RL-MPC-LaneMerging-master/autonomous-learning-library-0.5.3/autonomous-learning-library-0.5.3/examples/slurm_experiment.py", line 6, in <module>
    from all.experiments import SlurmExperiment
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\__init__.py", line 1, in <module>
    from .run_experiment import run_experiment
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\run_experiment.py", line 1, in <module>
    from .single_env_experiment import SingleEnvExperiment
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\single_env_experiment.py", line 3, in <module>
    from .writer import ExperimentWriter
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\writer.py", line 83, in <module>
    COMMIT_HASH = get_commit_hash()
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\site-packages\all\experiments\writer.py", line 74, in get_commit_hash
    result = subprocess.run(
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jl\anaconda3\envs\pytorch\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Looking forward to your reply !!!!!

**Comment by cpnota** [comment]
The library attempts to tag runs with the git commit hash of the parent repository to help with reproducibility. You can fix this by initializing a git repository in your working directory. This should probably not be required, so I will add a bug label.

**Comment by cpnota** [comment]
Closed by #271 . Try the `develop` branch.
